<a href="https://colab.research.google.com/github/dgierejkiewicz/data-science/blob/master/algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
np.__version__

'1.18.5'

In [5]:
v1 = np.array([-1, 4])
v1

array([-1,  4])

In [6]:
np.linalg.norm(v1)

4.123105625617661

In [9]:
v2 = np.array([0, 0, 1])
v2

array([0, 0, 1])

In [10]:
np.linalg.norm(v2)

1.0

In [0]:
p = np.array([3, 0])
q = np.array([0, 4])

In [12]:
np.linalg.norm(p - q)

5.0

In [0]:
p = np.array([3, 0, 1])
q = np.array([0, 4, 2])

In [14]:
np.linalg.norm(p - q)

5.0990195135927845

In [3]:
# Mnożenie macieży

X = np.array([[5, 3], [3, 9]])
Y = np.array([[1], [-1]])
print(X, '\n')
print(Y)

[[5 3]
 [3 9]] 

[[ 1]
 [-1]]


In [5]:
Z = np.dot(X, Y)
Z

array([[ 2],
       [-6]])

In [6]:
Z.shape

(2, 1)

In [9]:
# Wyznacznik macieży
A = np.array([[2, 4], [-1, 3]])
A

array([[ 2,  4],
       [-1,  3]])

In [4]:
round(np.linalg.det(A))

10.0

In [5]:
# Ślad macierzy - suma wartości od a11 do ann (przekątna)
np.trace(A)

5

In [8]:
# Macierz jednostkowa z wartościami od a11 do ann = 1
A = np.eye(5, dtype='int')
A

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [10]:
# Macierz odwrotna (AB = BA = I)
A

array([[ 2,  4],
       [-1,  3]])

In [12]:
B = np.linalg.inv(A)
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [14]:
np.set_printoptions(precision=4, suppress=True)
np.dot(A, B)

array([[1., 0.],
       [0., 1.]])

In [15]:
np.dot(B, A)

array([[ 1., -0.],
       [ 0.,  1.]])

In [16]:
# Macierz transponowana (zamiana wierszy na kolumny)
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

In [17]:
A.T

array([[ 2, -1],
       [ 4,  3]])