<a href="https://colab.research.google.com/github/dgierejkiewicz/data-science/blob/master/array_indexing_cutting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [3]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [0]:
# A[idx], A[start:stop] , A[start:], A[:stop]

In [5]:
A[2]

2

In [6]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [7]:
A[:2]

array([0, 1])

In [8]:
A[[0, 2]]

array([0, 2])

In [9]:
A[-1]

19

In [10]:
A[10:15]

array([10, 11, 12, 13, 14])

In [12]:
A = A.reshape(4, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [13]:
A[1]

array([5, 6, 7, 8, 9])

In [14]:
A[0]

array([0, 1, 2, 3, 4])

In [15]:
A[:,0]

array([ 0,  5, 10, 15])

In [16]:
A[:,-2]

array([ 3,  8, 13, 18])

In [18]:
A[1,1]

6

In [19]:
A[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])