<a href="https://colab.research.google.com/github/dgierejkiewicz/data-science/blob/master/array_basic_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 4])

In [0]:
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  4]


In [0]:
np.add(A, B)

array([6, 0, 7, 6])

In [0]:
A + B

array([6, 0, 7, 6])

In [0]:
np.subtract(A, B)

array([ 0,  2,  1, -2])

In [0]:
A - B

array([ 0,  2,  1, -2])

In [0]:
B - A

array([ 0, -2, -1,  2])

In [0]:
np.multiply(A, B)

array([ 9, -1, 12,  8])

In [0]:
A * B

array([ 9, -1, 12,  8])

In [0]:
np.divide(A, B)

array([ 1.        , -1.        ,  1.33333333,  0.5       ])

In [0]:
A / B

array([ 1.        , -1.        ,  1.33333333,  0.5       ])

In [0]:
A + 3

array([6, 4, 7, 5])

In [0]:
1.2 * A

array([3.6, 1.2, 4.8, 2.4])

In [0]:
A + 3*B

array([12, -2, 13, 14])

In [7]:
X = np.array([[1, 3], [-2, 3]])
Y = np.array([[6, 0], [-1, 2]])
print(X)
print(Y)

[[ 1  3]
 [-2  3]]
[[ 6  0]
 [-1  2]]


In [4]:
X * Y

array([[6, 0],
       [2, 6]])

In [5]:
np.dot(X, Y)

array([[  3,   6],
       [-15,   6]])

In [8]:
np.dot(Y, X)

array([[ 6, 18],
       [-5,  3]])

In [9]:
X.dot(Y)

array([[  3,   6],
       [-15,   6]])

In [10]:
Y.dot(X)

array([[ 6, 18],
       [-5,  3]])