<a href="https://colab.research.google.com/github/dgierejkiewicz/data-science/blob/master/array_basic_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 4])

In [4]:
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  4]


In [13]:
np.add(A, B)

array([6, 0, 7, 6])

In [5]:
A + B

array([6, 0, 7, 6])

In [14]:
np.subtract(A, B)

array([ 0,  2,  1, -2])

In [6]:
A - B

array([ 0,  2,  1, -2])

In [7]:
B - A

array([ 0, -2, -1,  2])

In [15]:
np.multiply(A, B)

array([ 9, -1, 12,  8])

In [8]:
A * B

array([ 9, -1, 12,  8])

In [16]:
np.divide(A, B)

array([ 1.        , -1.        ,  1.33333333,  0.5       ])

In [9]:
A / B

array([ 1.        , -1.        ,  1.33333333,  0.5       ])

In [10]:
A + 3

array([6, 4, 7, 5])

In [11]:
1.2 * A

array([3.6, 1.2, 4.8, 2.4])

In [12]:
A + 3*B

array([12, -2, 13, 14])