<a href="https://colab.research.google.com/github/dgierejkiewicz/data-science/blob/master/intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("Hello colab")

Hello colab


In [0]:
import numpy as np

In [4]:
np.__version__

'1.18.4'

In [0]:
help(np.array)

In [10]:
x = np.array([1,3])
x

array([1, 3])

In [11]:
x.ndim

1

In [12]:
x.shape

(2,)

In [13]:
x.size

2

In [14]:
x.dtype

dtype('int64')

In [17]:
x = np.array([[1, 2],[3, -1]])
x

array([[ 1,  2],
       [ 3, -1]])

In [18]:
x.ndim

2

In [19]:
x.shape

(2, 2)

In [22]:
x = np.array([[1, 3, 2], [-1, 0, 3]])
print(x)

[[ 1  3  2]
 [-1  0  3]]
