<a href="https://colab.research.google.com/github/dgierejkiewicz/data-science/blob/master/numpy_data_types.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
A = np.array([1,3])
A

array([1, 3])

In [4]:
A.dtype

dtype('int64')

In [5]:
A = np.array([1.0, 3.0, 4.1])
A

array([1. , 3. , 4.1])

In [6]:
A.dtype

dtype('float64')

In [9]:
A = np.array([1, 3, 4], dtype='float')
A

array([1., 3., 4.])

In [8]:
A.dtype

dtype('float64')

In [0]:
A = np.array([1, 3, 4], dtype='complex')

In [11]:
A.dtype

dtype('complex128')