<a href="https://colab.research.google.com/github/dgierejkiewicz/data-science/blob/master/numpy_funkcje_statystyczne.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
np.__version__

'1.18.5'

In [4]:
price = np.array([[12.40, 12.80, 11.90, 12.60, 1000],
                  [12.50, 13.00, 11.70, 12.20, 2000],
                  [12.20, 13.40, 12.20, 13.20, 1500]])
price

array([[  12.4,   12.8,   11.9,   12.6, 1000. ],
       [  12.5,   13. ,   11.7,   12.2, 2000. ],
       [  12.2,   13.4,   12.2,   13.2, 1500. ]])

In [5]:
price.sum() # lub np.sum(price)

4650.1

In [6]:
price.sum(axis=0) # Sumowanie po kolumnach

array([  37.1,   39.2,   35.8,   38. , 4500. ])

In [7]:
price.sum(axis=1) # Sumowanie po wierszach

array([1049.7, 2049.4, 1551. ])

In [8]:
np.min(price)

11.7

In [9]:
np.min(price, axis=0) # Minimum z kolumn

array([  12.2,   12.8,   11.7,   12.2, 1000. ])

In [10]:
np.min(price, axis=1) # Minimum z wierszy

array([11.9, 11.7, 12.2])

In [11]:
np.median(price)

12.6

In [15]:
np.set_printoptions(precision=4, suppress=True)
np.mean(price, axis=0) # Średnia cena po kolumnach

array([  12.3667,   13.0667,   11.9333,   12.6667, 1500.    ])

In [16]:
np.std(price, axis=0) # Odchylenie standardowe po kolumnach

array([  0.1247,   0.2494,   0.2055,   0.411 , 408.2483])

In [17]:
np.var(price, axis=0) # Wariancja po kolumnach

array([     0.0156,      0.0622,      0.0422,      0.1689, 166666.6667])