<a href="https://colab.research.google.com/github/dgierejkiewicz/data-science/blob/master/rozwiazywanie_rownan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
np.__version__

'1.18.5'

In [2]:
# AX = B
# (A^-1)AX = (A^-1)B
# X = (A^-1)B

A = np.array([[2, 4], [1, -1]])
A

array([[ 2,  4],
       [ 1, -1]])

In [4]:
B = np.array([[10], [-1]])
B

array([[10],
       [-1]])

In [5]:
A_inv = np.linalg.inv(A)
A_inv

array([[ 0.16666667,  0.66666667],
       [ 0.16666667, -0.33333333]])

In [6]:
X = np.dot(A_inv, B)
X

array([[1.],
       [2.]])

In [7]:
X.shape

(2, 1)